version: '3.4'

services:
  auth:
    image: gps-tracker-auth
    depends_on:
      - mongo

    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      JWT_SECRET: example
    
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    ports:
      - 8081:8081